name: latestBuild

on:
  push:

jobs:
  latestBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: build
        run: ./cross-compile.sh
      - name: delete old "latest" release
        run: |
          gh release delete latest -y || true
          git tag -f latest
          git push --force origin latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: create release
        run: gh release create latest --title latest --notes "latest build of main branch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload artifacts
        run: gh release  upload latest dist/bin/*.gz dist/bin/*.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
